version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - rm package-lock.json
      - npm install

  pre_build:
    commands:
      - node -v
      - pwd
      - ls

  build:
    commands:
      - echo "Building the project..."
      - npm run build

  post_build:
    commands:
      - echo "Packaging the project..."
      - cp -r node_modules dist
      - cd dist
      - ls
      - zip -r lambda.zip .
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda.zip
      - echo "Deployment completed."

    finally:
      - echo "Cleaning up..."
      - cd ..
      - ls
      - rm ./*
