version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - rm package-lock.json
      - npm install
  build:
    commands:
      - echo "Building the project..."
      - npm run build
  post_build:
    commands:
      - echo "Packaging the project..."
      - cp -r node_modules dist
      - cd dist
      - zip -r lambda.zip .
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file lambda.zip
      - echo "Deployment completed."
