# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "lambda/**"
      - ".github/workflows/node.js.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: ./lambda/package-lock.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
        working-directory: ../

      - name: Install dependencies
        run: |
          npm install
          npm run prebuild
          npm run build
        working-directory: ./lambda

      - name: Check diff
        id: git-diff
        run: git diff

      - name: Commit and push changes
        if: steps.git-diff.outputs.stdout != ''
        run: |
          git add .
          git commit -m "Transpiled dist files by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
